version: '2'

services:
  app:
    image: harmony/portfolio
    build: .
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:hrmny.pw"
      - "traefik.port=3000"
    volumes:
      - /data/portfolio:/app/public/data

networks:
  web:
    external:
      name: traefik_webgateway
